---
title: "Programa de Prevenci칩n & Control del Dengue | 2025"
format: 
  dashboard:
      nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup_14_jalisco}
library(sf)
mapview::mapviewOptions(default = TRUE,
                        basemaps.color.shuffle = FALSE)
if(as.vector(Sys.info()["sysname"]) == "Darwin"){
load("/Users/fdzul/Documents/geocoding_mx/2025/8.RData/denmex_2025.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Windows"){
   load("D:\\OneDrive\\proyects\\geocoding_mex\\2024\\8.RData\\denmex_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Linux"){
    load("/home/fdzul/Documents/active_transmission/geocoding_mx/8.RData/denmex_2025.RData")
}
library(magrittr)
```


# [**Cadenas de Transmisi칩n**]{style="font-size:8pt"}

::: panel-tabset

### [**Guadalajara**]{style="color:#990000"}

```{r chains_guadalajara}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "14",
                                     locality = c("Guadalajara", 
                                                  "Tlaquepaque",
                                                  "Zapopan", 
                                                  "Tonal치"),
                                     dengue_cases = "Confirmado")
```


### [**Puerto Vallarta**]{style="color:#990000"}
```{r cadenas_puerto_vallarta}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "14",
                                     locality = "Puerto Vallarta",
                                     dengue_cases = "Confirmado")
```

:::


# [**Mapas de Calor**]{style="font-size:8pt"}

::: panel-tabset

### [**Guadalajara**]{style="color:#990000"}

```{r heatmap_guadalajara}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "14",
                   locality = c("Guadalajara", 
                                "Tlaquepaque",
                                "Zapopan", 
                                "Tonal치"),
                   status_caso = c(1, 2),
                   kernel = 80,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```


### [**Puerto Vallarta**]{style="color:#990000"}

```{r heatmap_puerto_vallarta}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "14",
                   locality = "Puerto Vallarta",
                   status_caso = c(1, 2),
                   kernel = 500,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```

:::


